### ISSUE TITLE
Not autoscaling on deployment

### ISSUE THREAD

**Issue by kkozmic-seek** [ThoughtWorksStudios/eb_deployer#47]
Here's our scenario:

We have 2-6 instances in autoscaling group configuration.

Let's say we're currently running with 4 instances live and do a deployment. When eb_deployer does the switch over it doesn't bring 4 instances online, it switches over to the minimum, which is 2. So we're smashing our poor 2 instances with double the load they should take.

I would expect that before doing the switch eb_deployer would make sure that the same number of instances is ready to handle the initial load.

Is there a way to make it work that way? Is this on the roadmap at all?

**Comment by wpc** [comment]
Hi, kkozmic:

There is no out-of-box way unless AWS autoscale group support a "Init-Size" option. (Some feature request we can make I guess :-))
But In your case you can write some script in "smoke-test" section to hit the inactive environment hard to make it scale up before DNS switch (I suggest use apache ab http://httpd.apache.org/docs/2.2/programs/ab.html ).  I have use this trick to warm up JVMs for a java service with success.

-- wpc

**Comment by kkozmic-seek** [comment]
hey @wpc thanks for the response.

Yeah, I just implemented a smoke-test hack to pre-heat the ELB but I'd much rather have a nice, supported way in eb_deployer (and AWS) to do it differently.

My hack feels... hacky and slow :)

**Comment by wpc** [comment]
Scheduled scaling (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html#command-options-general-autoscalingscheduledaction) may be another option for this problem. Something like following may work:
````yaml
    option_settings:
      - namespace: aws:autoscaling:asg
        option_name: MinSize
        value: "2"
      - namespace: aws:autoscaling:asg
        option_name: MaxSize
        value: "6"
      - namespace: aws:autoscaling:scheduledaction
        option_name: DesiredCapacity
        value: "4"
      - namespace: aws:autoscaling:scheduledaction
        option_name: StartTime
        value: "<%= (Time.now.utc + 5).iso8601 %>"
````

BTW I haven't have time to try it myself yet. If you want to play around with it, let me know the result.
