### ISSUE TITLE
Setting LoadBalancer Security Groups by id or values

### ISSUE THREAD

**Issue by ezjacob-maheim** [ThoughtWorksStudios/eb_deployer#58]
Is there a way to either set/create the security groups for the load balancer?

**Comment by wpc** [comment]
hi, @ezjacob-maheim:

AWS ELB instances by default belongs to amazon-elb-sg security group (sg-843f59ed). AWS ElasticBeanstalk automatically sets up EC2 instances security group to trust all traffic from that group. Means by default traffic from ELB service are trusted.

If you need better fine-grain control, such as  locking down traffic to the specific ELB instance, you will need extend the default CloudFormation template. Drop a config file into the .ebextensions folder with resources declaration to override default settings.

````yaml
Resources:
  AWSEBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group to allow HTTPS for the elb"
      SecurityGroupIngress:
        - #  ingress rule on 80/443 only allow elb security group 
  AWSEBLoadBalancer:
    Type: "AWS::ElasticLoadBalancing::LoadBalancer"
    Properties:
      Listeners:
        - #listeners config
      HealthCheck:
       - #health check config
     SecurityGroups:
       - #give the elb a security group.
````

The resource name "AWSEBSecurityGroup" and "AWSEBLoadBalancer" are the default resources name in the CloudFormation template that EB generated. So it is important to keep the same. Other than it is just writing CF template in yaml instead of json.

**Comment by ezjacob-maheim** [comment]
@wpc Thanks for the info. I was able to attach a security group to the LB using AWSEBLoadBalancer resource. But the issue is I want the LB to terminate certain port from certain ip ranges. AWSEBLoadBalancer didn't allow me to do that. It just added the default security group and my more limited security group both to the LB.

**Comment by wpc** [comment]
hi, @ezjacob-maheim:
>> "I want the LB to terminate certain port from certain ip ranges"

Do you mean you want limit the public access to your LB using IP range?  If that is the case then I am totally misunderstand your original question. I thought you want to lock down the access to your backend instance to a specific LB instance.

As I know of there is no way you can lock down public access to ELB, unless the load balancer is a internal one in VPC. (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-security-groups.html#using-elb-security-groups).

**Comment by ezjacob-maheim** [comment]
@wpc thanks for the help. I actually figured it out. Its the same idea as what you've showed me. The Resource is AWSEBLoadBalancerSecurityGroup. Took me awhile to figure this out. Thanks for the help

```yml
  AWSEBLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: IP_RANGE
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp:IP_RANGE
```
