### ISSUE TITLE
Environment variables w/ "\n" fail

### ISSUE THREAD

**Issue by fredkelly** [ThoughtWorksStudios/eb_deployer#64]
Firstly, this is a great tool, thank you for creating it!

I'm finding a little niggle trying to set an environment variable that is read from a file (i.e. containing newline characters).

I have something like this (see [YAML doc](http://www.yaml.org/spec/1.2/spec.html#id2794534)):
```yaml
# config/eb_deployer.yml
      - namespace: aws:elasticbeanstalk:application:environment
        option_name: MY_VAR
        value: |
          First line
          Second line
```

If I load this through IRB, all is fine:
```ruby
require 'yaml'
deployer = YAML.load_file('config/eb_deployer.yml')
deployer['environments']['staging']['option_settings'].select{|opt| opt['option_name'] =='MY_VAR'}.first['value']
=> "First line\nSecond line"
```

When I come to run a deployment using the gem, I get an error:
```
(Namespace: 'aws:cloudformation:template:parameter', OptionName: 'EnvironmentVariables'): Not a List of Key/Value pairs.
```

Is there a way I can include file values in `ENV` that contain newlines without error?

Much appreciated!
