### ISSUE TITLE
CloudFormation config structure question

### ISSUE THREAD

**Issue by darrenhaken** [ThoughtWorksStudios/eb_deployer#91]
Is it possible to structure the CF config like this:
```
option_settings:
  aws:elb:listener:443:
    ListenerProtocol: HTTPS
    SSLCertificateId: arn:aws:iam::123456789012:server-certificate/elastic-beanstalk-x509
    InstancePort: 80
    InstanceProtocol: HTTP
  aws:elb:listener:80:
    ListenerEnabled: false
```

Rather than:

```
- namespace: aws:elb:listener:80
      option_name: ListenerEnabled
      value: "false"
```
